export const TYPES = {
  HttpClient: Symbol.for('HttpClient'),
  AudienceRepository: Symbol.for('AudienceRepository'),
  ListUserAudiencesUseCase: Symbol.for('ListUserAudiencesUseCase'),
  FetchDefaultAudiencesUseCase: Symbol.for('FetchDefaultAudiencesUseCase'),
  GetAudienceTemplateByIdUseCase: Symbol.for('GetAudienceTemplateByIdUseCase'),
  CreateAudienceUseCase: Symbol.for('CreateAudienceUseCase'),
  GetAudienceByIdUseCase: Symbol.for('GetAudienceByIdUseCase'),
  UpdateAudienceUseCase: Symbol.for('UpdateAudienceUseCase'),
  AddCommunityToAudienceUseCase: Symbol.for('AddCommunityToAudienceUseCase'),
  RemoveCommunityFromAudienceUseCase: Symbol.for('RemoveCommunityFromAudienceUseCase'),
  GetAudienceSuggestionsUseCase: Symbol.for('GetAudienceSuggestionsUseCase'),
  DeleteAudienceUseCase: Symbol.for('DeleteAudienceUseCase'),
  GetAudienceKeywordsUseCase: Symbol.for('GetAudienceKeywordsUseCase'),
  MarkCommunityNotRelevantUseCase: Symbol.for('MarkCommunityNotRelevantUseCase'),
  GetAudienceTopicsUseCase: Symbol.for('GetAudienceTopicsUseCase'),
  CommunityRepository: Symbol.for('CommunityRepository'),
  BrowseCommunitiesUseCase: Symbol.for('BrowseCommunitiesUseCase'),
  AuthRepository: Symbol.for('AuthRepository'),
  LoginUseCase: Symbol.for('LoginUseCase'),
  RegisterUseCase: Symbol.for('RegisterUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  GetMeUseCase: Symbol.for('GetMeUseCase'),
} as const
